AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'bundle_bin/**/*'

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

DoubleNegation:
  Enabled: false
