require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: '3.0'
  NewCops: enable
  Include:
    - 'app/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'spec/example.txt'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'bundle_bin/**/*'
    - 'Guardfile'
    - 'node_modules/**/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

# シリアライズに使うときはtrue/falseでないと困る
Style/DoubleNegation:
  Enabled: false

# 日本語なのでwhenとかの単語では始められない
RSpec/ContextWording:
  Enabled: false

# beforeは目的ごとにグループ分けして書きたい
RSpec/ScatteredSetup:
  Enabled: false

# shoulda-matchersのcontrollerで使う
RSpec/ImplicitSubject:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
