version: '3'

volumes:
  data: {}

services:
  rproxy:
    build:
      context: '.'
      dockerfile: './containers/rproxy/Dockerfile'
    image: 'ktachiv/russ-rproxy'
    links:
      - webapp
    ports:
      - '80:80'
    restart: always

  app-base: &app-base
    image: 'ktachiv/russ'
    environment:
      DATABASE_URL: 'postgres://postgres@database/postgres'
    env_file: docker-app.env
    command: /bin/true

  app-build:
    <<: *app-base
    build: '.'

  webapp:
    <<: *app-base
    links:
      - database
    command: ['rails', 'app:server']
    ports:
      - '3000:3000'
    restart: always

  crawler:
    <<: *app-base
    links:
      - database
    command: ['rails', 'app:crawler']
    restart: always

  database:
    image: 'postgres:9.5'
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  app-oneoff:
    <<: *app-base
    links:
      - database
    command: /bin/true
    restart: 'no'

  db-oneoff:
    image: 'postgres:9.5'
    links:
      - database
    environment:
      PGHOST: database
      PGUSER: postgres
    command: /bin/true
    restart: 'no'
