version: '3'

volumes:
  data: {}

services:
  app-base: &app-base
    image: 'ktachiv/russ'
    environment:
      DATABASE_URL: 'postgres://postgres@database/postgres'
    env_file: docker-app.env
    command: /bin/true

  rproxy:
    <<: *app-base
    links:
      - webapp
    ports:
      - '80:80'
    command: ["nginx", "-g", "daemon off;"]

  app-build:
    <<: *app-base
    build: '.'

  webapp:
    <<: *app-base
    links:
      - database
    command: ['/russ/bin/rails', 'app:server']
    ports:
      - '3000:3000'

  crawler:
    <<: *app-base
    links:
      - database
    command: ['rails', 'app:crawler']

  database:
    image: 'postgres:9.5'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app-oneoff:
    <<: *app-base
    links:
      - database
    command: /bin/true

  db-oneoff:
    image: 'postgres:9.5'
    links:
      - database
    environment:
      PGHOST: database
      PGUSER: postgres
    command: /bin/true
