reverseproxy:
  build: 'containers/reverse-proxy'
  links:
    - webapp
  volumes_from:
    - webapp
    - datastore
  ports:
    - '80:80'

webapp:
  build: 'containers/webapp'
  links:
    - database
  volumes_from:
    - datastore
  env_file: .env

crawler:
  build: 'containers/crawler'
  links:
    - database
  volumes_from:
    - datastore
  env_file: .env

database:
  image: 'postgres:latest'
  volumes_from:
    - datastore
  env_file: .env

datastore:
  build: 'containers/datastore'
