rproxy:
  build: './'
  dockerfile: './containers/rproxy/Dockerfile'
  links:
    - webapp
  expose:
    - '80'
  environment:
    VIRTUAL_HOST: $VIRTUAL_HOST
    LETSENCRYPT_HOST: $VIRTUAL_HOST
    LETSENCRYPT_EMAIL: deadzone@be.to
  restart: always

app:
  image: 'ktachiv/russ'
  environment:
    DATABASE_URL: 'postgres://postgres@database/postgres'
  command: /bin/true

webapp:
  extends:
    service: app
  links:
    - database
  volumes_from:
    - datastore
  command: ['rake', 'app:server']
  expose:
    - 8080
  restart: always

crawler:
  extends:
    service: app
  links:
    - database
  volumes_from:
    - datastore
  command: ['rake', 'app:crawler']
  mem_limit: 512m
  restart: always

database:
  image: 'postgres:9.5'
  volumes_from:
    - datastore
  restart: always

app-env:
  extends:
    service: app
  links:
    - database
  volumes_from:
    - datastore
  command: /bin/true

database-client:
  image: 'postgres:9.5'
  links:
    - database
  environment:
    PGHOST: database
    PGUSER: postgres
  command: /bin/true

datastore:
  image: 'busybox:latest'
  volumes:
    - /var/lib/postgresql/data
    - /russ/config/vars
  command: /bin/true
