webapp:
  build: '.'
  links:
    - database
  volumes_from:
    - datastore
  ports:
    - '8080'
  command: ['unicorn_rails', '-c', 'config/unicorn.rb']
  env_file: .env

crawler:
  build: '.'
  links:
    - database
  command: ['rake', 'russ:crawler']
  env_file: .env

database:
  image: 'postgres:9.5'
  volumes_from:
    - datastore

datastore:
  build: 'containers/datastore'
