default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

production:
  <<: *default
  database: russ
  password: '<%= ENV['MYSQL_ENV_MYSQL_ROOT_PASSWORD'] %>'
  host: '<%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>'
  port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] %>
